//
// Code generated by grafana-app-sdk. DO NOT EDIT.
//

package v0alpha1

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// schema is unexported to prevent accidental overwrites
var (
	schemaAlertingStatus = resource.NewSimpleSchema("admin.alerting.grafana.app", "v0alpha1", NewAlertingStatus(), &AlertingStatusList{}, resource.WithKind("AlertingStatus"),
		resource.WithPlural("alertingstatuses"), resource.WithScope(resource.NamespacedScope))
	kindAlertingStatus = resource.Kind{
		Schema: schemaAlertingStatus,
		Codecs: map[resource.KindEncoding]resource.Codec{
			resource.KindEncodingJSON: &AlertingStatusJSONCodec{},
		},
	}
)

// Kind returns a resource.Kind for this Schema with a JSON codec
func AlertingStatusKind() resource.Kind {
	return kindAlertingStatus
}

// Schema returns a resource.SimpleSchema representation of AlertingStatus
func AlertingStatusSchema() *resource.SimpleSchema {
	return schemaAlertingStatus
}

// Interface compliance checks
var _ resource.Schema = kindAlertingStatus
