//
// Code generated by grafana-app-sdk. DO NOT EDIT.
//

package v0alpha1

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// schema is unexported to prevent accidental overwrites
var (
	schemaAlertingSummary = resource.NewSimpleSchema("admin.alerting.grafana.app", "v0alpha1", NewAlertingSummary(), &AlertingSummaryList{}, resource.WithKind("AlertingSummary"),
		resource.WithPlural("alertingsummaries"), resource.WithScope(resource.NamespacedScope))
	kindAlertingSummary = resource.Kind{
		Schema: schemaAlertingSummary,
		Codecs: map[resource.KindEncoding]resource.Codec{
			resource.KindEncodingJSON: &AlertingSummaryJSONCodec{},
		},
	}
)

// Kind returns a resource.Kind for this Schema with a JSON codec
func AlertingSummaryKind() resource.Kind {
	return kindAlertingSummary
}

// Schema returns a resource.SimpleSchema representation of AlertingSummary
func AlertingSummarySchema() *resource.SimpleSchema {
	return schemaAlertingSummary
}

// Interface compliance checks
var _ resource.Schema = kindAlertingSummary
