//
// Code generated by grafana-app-sdk. DO NOT EDIT.
//

package v0alpha1

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// schema is unexported to prevent accidental overwrites
var (
	schemaSummary = resource.NewSimpleSchema("admin.alerting.grafana.app", "v0alpha1", NewSummary(), &SummaryList{}, resource.WithKind("Summary"),
		resource.WithPlural("summaries"), resource.WithScope(resource.NamespacedScope))
	kindSummary = resource.Kind{
		Schema: schemaSummary,
		Codecs: map[resource.KindEncoding]resource.Codec{
			resource.KindEncodingJSON: &SummaryJSONCodec{},
		},
	}
)

// Kind returns a resource.Kind for this Schema with a JSON codec
func SummaryKind() resource.Kind {
	return kindSummary
}

// Schema returns a resource.SimpleSchema representation of Summary
func SummarySchema() *resource.SimpleSchema {
	return schemaSummary
}

// Interface compliance checks
var _ resource.Schema = kindSummary
